vich_uploader:
    db_driver: orm
    
    mappings:
        restaurant_image:
            uri_prefix: '%restaurant_image_attachments%'
            upload_destination: '%kernel.project_dir%/public%restaurant_image_attachments%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
        plat_image:
            uri_prefix: '%plat_image_attachments%'
            upload_destination: '%kernel.project_dir%/public%plat_image_attachments%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
